"""empty message

Revision ID: 4e01bd72bb4a
Revises: 32f128629b50
Create Date: 2015-12-09 11:55:21.489720

"""

# revision identifiers, used by Alembic.
revision = '4e01bd72bb4a'
down_revision = '32f128629b50'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'roles', ['name'])
    op.create_unique_constraint(None, 'tags', ['tag'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags')
    op.drop_constraint(None, 'roles')
    ### end Alembic commands ###
